### ISSUE TITLE
Can not install on Julia 1.0.1 

### ISSUE THREAD

**Issue by mbeltagy** [Evizero/Augmentor.jl#28]
```julia 
v1.0) pkg> add Augmentor
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Augmentor [0612f1b9]:
 Augmentor [0612f1b9] log:
 ├─possible versions are: [0.0.1-0.0.2, 0.1.0, 0.2.0, 0.3.0-0.3.1, 0.4.0, 0.5.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.2, 0.1.0, 0.2.0, 0.3.0-0.3.1, 0.4.0, 0.5.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
(v1.0) pkg> dev Augmentor
   Cloning git-repo `https://github.com/Evizero/Augmentor.jl.git`
  Updating git-repo `https://github.com/Evizero/Augmentor.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ShowItLikeYouBuildIt [9966252f]:
 ShowItLikeYouBuildIt [9966252f] log:
 ├─possible versions are: [0.0.1, 0.1.0-0.1.1, 0.2.0] or uninstalled
 ├─restricted to versions 0.0.0-* by Augmentor [0612f1b9], leaving only versions [0.0.1, 0.1.0-0.1.1, 0.2.0]
 │ └─Augmentor [0612f1b9] log:
 │   ├─possible versions are: 0.5.0 or uninstalled
 │   └─Augmentor [0612f1b9] is fixed to version 0.5.0+
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

```

**Comment by Evizero** [comment]
yes its not upgraded yet

**Comment by mbeltagy** [comment]
Can I help?

**Comment by Evizero** [comment]
Thank you for offering, but I am afraid not. The remaining hurdles need some rewrite of the internals and some rethinking of the tests. The current state of the update is in #27 . You can try if that works for you.

**Comment by merl-dev** [comment]
I have been working on an upgrade to 1.x, now focused on the tests with about 2/3rds complete.  Should be done by Sunday.  My focus has been on getting it to work and not looking at performance / optimization...yet.

**Comment by Evizero** [comment]
That sounds cool! Did you start with #27 as a basis? because i contains quite a bit of changes that are important

**Comment by merl-dev** [comment]
I started with the update0.7 branch assuming it contained those changes that you had implemented. 

**tests passing**
utils, augmentbatch, ops-dims, ops-convert, ops-noop, ops-cache, ops-shear, ops-flip, ops-crop, ops-resize, ops-scale, ops-zoom, ops-either, ops-channels

**failing**
- ops-mapfun: inference, return types
- ops-rotation: permute due to StepRange
- pipeline: StepRange
- distortedview: accessing IdentityUnitRange with indices -1:0 plus summary/showarg
- ops-distortions: accessing IdentityUnitRange with indices -1:0
- augment: BoundsError vs ArgumentError

Some of this is trivial, some may require some rethink.  I'll be pushing all of this on Friday.

**Comment by Evizero** [comment]
If you open a PR against `update0.7` I'll be happy to provide feedback

**Comment by flare9x** [comment]
How are things coming along?

**Comment by johnnychen94** [comment]
With Augmentor v0.6.0 released, this can be closed now.
